### ISSUE TITLE
A single API call will start 4 process?

### ISSUE THREAD

**Issue by xsmart** [google/sandboxed-api#74]
I use below test code, and the test code  is:
StringopSapiSandbox sandbox;
ASSERT_THAT(sandbox.Init(), IsOk());
StringopApi api(&sandbox);
stringop::StringReverse proto;
proto.set_input("Hello");
sapi::v::Proto<stringop::StringReverse> pp(proto);
SAPI_ASSERT_OK_AND_ASSIGN(int return_value, api.pb_reverse_string(pp.PtrBoth()));
EXPECT_THAT(return_value, Ne(0)) << "pb_reverse_string() failed";
SAPI_ASSERT_OK_AND_ASSIGN(auto pb_result, pp.GetMessage());
LOG(INFO) << "Result PB: " << pb_result.DebugString();
EXPECT_THAT(pb_result.output(), StrEq("olleH"));

I find the framework will create 4 process:
user      13114   1174  0 01:40 pts/1    00:00:00 ./main_stringop
user      13115  13114  0 01:40 pts/1    00:00:00 S2-FORK-SERV
user      13116  13115  0 01:40 ?        00:00:00 stringop-sapi.bin --logtostderr=true
user      13120  13116  0 01:40 ?        00:00:00 stringop-sapi.bin --logtostderr=true
user      13121  13120  0 01:40 ?        00:00:00 stringop-sapi.bin --logtostderr=true
why need 3 worker process

**Comment by happyCoder92** [comment]
This is working as intended.

S2-FORK-SERV is a global forkserver, there should be one per process using SAPI.
It's there so that we can safely fork and set up a sandboxee (no need to worry about locks being held etc.) and also does some preinitialization so that subsequent sandboxees start faster.

The first stringop-sapi.bin is a unsandboxed custom forkserver started for this particular library.
It's there so that the library is loaded/initialized only once and then the process can be just forked for new each sanboxee.

The last 2 processes are the actual sanboxee.
First one being the init process of the pid namespace and the second running the library - if namespaces are used (recommended) there will be always 2 processes per sandboxee instance.
