### ISSUE TITLE
Do the framework support multi so in different folder?

### ISSUE THREAD

**Issue by xsmart** [google/sandboxed-api#77]
we have a SDK has multi so and in different folder, and the SDK also dynamic load some so such as libssl.so, can framework support these case?
![image](https://user-images.githubusercontent.com/4601085/103844923-f72b5380-50d5-11eb-8b8e-5ac645940393.png)

**Comment by cblichmann** [comment]
Yes, this is also supported.

You will need to use `PolicyBuilder::AddFile()`/`PolicyBuilder::AddFileAt()` to map these files. Since they are likely dynamically linked against libc and/or other libraries as well, you can also try to use `PolicyBuilder::AddLibrariesForBinary()`, which uses a minimal ELF parser to find dependant libraries and makes them available in the sandbox.

Note that while we do support this use case, the best course of action would be to statically link the SDK if that is possible. The reason is that you can further restrict the syscalls the sandboxee is allowed to make (dynamic startup needs to allow quite a few). For OpenSSL (`libcrypto` and `libssl`), this is respnably straight-forward. Similar for libiconv.

**Comment by xsmart** [comment]
Great ! Thanks
