### ISSUE TITLE
Can this be globally installed?

### ISSUE THREAD

**Issue by jamespharvey20** [google/sandboxed-api#9]
i.e. Can a Linux distribution provide this as a package, or must users download it to and run it out of their user directory?  (I'm working on adding this to the Arch User Repository.)

I was able to compile this on Arch Linux, using `bazel build ...`

What are the next steps?  The few Arch packages for projects using Bazel have a handful of things manually copied, but I see there are 3700+ entries in `bazel-bin/`, in `_solib_k8/`, `external`, and `sandboxed_api`.

`bazel query //...` doesn't show anything that looks like an install target.

**Comment by cblichmann** [comment]
Short answer: Not right now. If you're using Bazel to develop your code, you can depend on our Bazel workspace in order to make use of Sandboxed API and everything will work as expected.
I do of course realize that this is not how everyone does development. So we do plan to support CMake as an additional build system. Then the packaging for distributions will become a lot easier, as you can depend on system libraries and don't have to ship/compile everything you depend on.
I filed #10 for this.
